# Generated by Django 5.2.8 on 2025-11-13 03:13

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lalafo_app', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
